branches:
  only:
  - prod

image:
- macOS-BigSur
- Ubuntu2004

platform:
- x64

init:
- git config --global core.autocrlf input
- sh: >-
    if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "macOS-BigSur" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi

environment:
  GH_TOKEN:
    secure: exT+ILSz9YTmPsT/jYGNzzgLSsfv8J9xOqMdxR0PzXv1GJhG8Oo5Cp3b09W110j6
  APPLE_ID: jeff@myassurehealth.com
  APPLE_ID_PASS:
    secure: A0LpNyxUtq96F6i1xPuJ78jjgvON9XzvTf0+dLJnTJA=
  CSC_LINK:
    secure: nrq/jC+5MMZEgIGsA+ejpMbMesryxFrndnGASjnL0EkOlg1zoO4PpM4Ni+g1xwf+AijmrohjoFVH1F6k6hqVcYUK1N8ZazfQ3g5g+9OtXOg1/rRopLBxTBfjsGuiu+am
  CSC_KEY_PASSWORD:
    secure: C3n1oFP1liniVK50TW0y8jGaQTfOYSMO/0T/Lm9SwBY=

stack: node 14

install:
- echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: >-
    if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2004" ]; then
      docker run --rm \
        -v $APPVEYOR_BUILD_FOLDER:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine /bin/bash -c \
        "npm install --legacy-peer-deps"
    else
      npm install --legacy-peer-deps
    fi

before_build:
- git lfs pull

build_script:
- sh: >-
    if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2004" ]; then
      docker run --rm \
        -v $APPVEYOR_BUILD_FOLDER:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine /bin/bash -c \
        "ANALYZE=true npm run build"
    else
      ANALYZE=true npm run build
    fi

test_script:
- sh: >-
    if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2004" ]; then
      docker run --rm \
        -v $APPVEYOR_BUILD_FOLDER:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine /bin/bash -c \
        "npm run test"
    else
      npm run test
    fi

deploy_script:
- sh: >-
    if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2004" ]; then
      docker run --rm \
        -v $APPVEYOR_BUILD_FOLDER:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine /bin/bash -c \
        "npm run release --linux AppImage --win"
    else
      npm run release
    fi
